### ISSUE TITLE
Great job! Congrat!

### ISSUE THREAD

**Issue by VietHoang1512** [tienlonghungson/RdB-Graduation-Slide#1]
Khét đấy

**Comment by tienlonghungson** [comment]
Baoh có NIPS

**Comment by VietHoang1512** [comment]
tháng 9, còn năm nào thì ko biết

**Comment by tienlonghungson** [comment]
nay đang thử học VIM. Test luôn trên overleaf mà thấy overleaf support VIM hơi hạn chế thì phải

**Comment by VietHoang1512** [comment]
t thì chịu, thử nhiều lần rồi ko học được https://missing.csail.mit.edu/2020/editors/

**Comment by tienlonghungson** [comment]
chơi thử cái VIM adventure chưa?
